### ISSUE TITLE
text_feat_extractor.py parameters 

### ISSUE THREAD

**Issue by qiaogh97** [chuhaojin/bottom-up-attention-ForApp#2]
#python text_feat_extractor.py 
Traceback (most recent call last):
  File "text_feat_extractor.py", line 82, in <module>
    vfe = TextFeatureExtractor(cfg_file, model_weights, gpu_id=1)
  File "text_feat_extractor.py", line 54, in __init__
    self.text_model.learnable.load_state_dict(text_model_component)
  File "/root/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ModuleDict:
        Unexpected key(s) in state_dict: "textencoder.backbone.bert.embeddings.position_ids".

**Comment by qiaogh97** [comment]
update transformers==4.5.1
